### ISSUE TITLE
Adding the wp header and footer for the admin bar

### ISSUE THREAD

**Issue by jasperkooij** [JunaidQadirB/awe-theme#1]
I was not able to get the admin bar but by removing
{{ wp_head }} 

And by adding 
{{ function('wp_head') }} 
and 
{{ function('wp_footer') }}

in base.twig, it is working fine for me.

That way I can use the debug bar and the timber debug bar to review templates and the page data:

<img width="1638" alt="Awe" src="https://user-images.githubusercontent.com/18720/58925320-af2f9800-870c-11e9-8fae-18de8ad8fff7.png">

And use the rest of the admin bar.

Thanks for your theme. I love the article as well!

**Comment by JunaidQadirB** [comment]
Thank you for the words of appreciation. Appreciated!!

Ah, I noticed I forgot to add `wp_footer`.

{{ wp_head }} and {{ wp_footer }} also work and in my opinion, they are shorter and sweeter than calling with Timer's `function`  function, nontheless, both work just fine.

Thanks for the feedback. I have updated the code in the repo as well as in the article.
