### ISSUE TITLE
How is jQuery used?

### ISSUE THREAD

**Issue by jasperkooij** [JunaidQadirB/awe-theme#6]
I'm implementing a bootstrap navbar with the drop-down menu but the drop-down portion of the standard navbar (https://getbootstrap.com/docs/4.3/components/navbar/) does not seem to be working.

What did I miss in the setup?

It is it that Jquery somehow is not working?

**Comment by JunaidQadirB** [comment]
jQuery that comes with WordPress should be being used.

Do you see any error in the inspector panel?
Also, can share the output of `console.log({$, jQuery})`

**Comment by jasperkooij** [comment]
I'm getting "Uncaught ReferenceError: $ is not defined
    at (index):44"
when I'm logged out and 

"JQMIGRATE: Migrate is installed, version 1.4.1
(index):65 {$: undefined, jQuery: ƒ}"

when I am logged in.

**Comment by JunaidQadirB** [comment]
Then, either you should swap all references to `$` with `jQuery`
or

wrap your js cod that uses `$` inside `document.ready` like this:

```javascript
jQuery(document).ready(function($){
 //your code that uses jquery's $
});
```

Can you come to gitter so that we can discuss this in realtime?

https://gitter.im/awe-theme/community

**Comment by jasperkooij** [comment]
Ok, I will give that a try and I will get a Gitter account
